# Generated by Django 4.2.23 on 2025-08-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('rides', '0002_alter_carclass_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.partnercompany')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(max_length=255, null=True)),
                ('trx_ref', models.CharField(max_length=255, null=True)),
                ('price_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('payment_link', models.TextField(null=True)),
                ('payment_id', models.TextField(null=True)),
                ('payment_intent', models.TextField(null=True)),
                ('reference_number', models.TextField(null=True)),
                ('card_type_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('channel', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rides.booking')),
            ],
            options={
                'permissions': [('can_view_payment', 'Can view payment'), ('can_update_payment', 'Can update payment'), ('can_delete_payment', 'Can delete payment')],
                'default_permissions': (),
            },
        ),
    ]
