# Generated by Django 4.2.23 on 2025-10-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='partner',
        ),
    ]
