# Generated by Django 4.2.23 on 2025-10-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_partnercompany_alter_driver_partner_and_more'),
        ('payments', '0002_remove_payout_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rides.partnercompany'),
            preserve_default=False,
        ),
    ]
