# Generated by Django 4.2.23 on 2025-10-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_partnercompany_alter_driver_partner_and_more'),
        ('payments', '0002_remove_payout_partner'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerCompany',
        ),
    ]
