# Generated by Django 4.2.23 on 2025-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_marketing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_sms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
