# Generated by Django 4.2.23 on 2025-10-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_admin', 'Peut ajouter un administrateur'), ('can_view_admin', 'Peut voir un administrateur'), ('can_view_dashboard', 'Peut voir le board'), ('can_update_admin', 'Peut mettre à jour un administrateur'), ('can_delete_admin', 'Peut supprimer un administrateur')],
                'default_permissions': (),
            },
        ),
    ]
