# Generated by Django 4.2.23 on 2025-10-20 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('payout_currency', models.CharField(default='EUR', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_add_company', 'Can add company'), ('can_view_company', 'Can view company'), ('can_update_company', 'Can update company'), ('can_delete_company', 'Can delete company')],
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='rides.partnercompany'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rides.partnercompany'),
        ),
    ]
