# Generated by Django 4.2.23 on 2025-08-18 13:12

from django.db import migrations, models
import rides.models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rides.models.car_class_upload_path),
        ),
    ]
