# Generated by Django 4.2.23 on 2025-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_carclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='person_capacity',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
