# Generated by Django 4.2.23 on 2025-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_partnercompany_alter_driver_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='phone',
            field=models.CharField(default=222, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
